exports.jayy = ['Perbedaan teman dan musuh sangat tipis. Ada saatnya dia mendukung berbagai hal yang kamu lakukan, tapi bisa saja dia menusuk dari belakang, bahkan menghancurkanmu.',
  'Dasar gak tahu berterima kasih! Makanya hidupnya bisa menderita seperti itu.',
  'Awas aja, apa yang dia lakukan sekarang bakal berbuah karma di kemudian hari.',
  'Kalau sudah berbicara tentang perasaan, sahabat pun berisiko jadi pelaku tikung menikung.',
  'Bahkan kayu yang berada di sungai selama puluhan tahun pun tak akan berubah menjadi buaya.',
  'Kata teman adalah label yang bisa dicoba siapa saja. Dan kaulah yang menentukan siapa yang paling pantas memakainya.',
  'Sekali-kali bolehlah menjadi orang yang jahat karena menjadi orang baik terus malah dimanfaatin sama teman sendiri.',
  'Terus aja ngomong, aku nguap kalau aku tertarik.',
  'Ada tujuh miliar orang di dunia ini. Kenapa kamu biarkan salah satu dari mereka menghancurkan hidupmu?.',
  'Oh, menderita? Makanya, jangan bikin susah orang.',
  'Hati-hati dengan mereka yang tak pernah sesuai antara ucapan dan tindakan.',
  'Silahkan ngomongin gue sepuasnya, gue hanya senyum saja karena gue tahu karena akan ada yang membalas.',
  'Tak seorang pun mempercayai pembohong. Sekalipun dia menceritakan kebenaran.',
  'Teman datang dan pergi, tapi aku tidak menyangka kamu juga.',
  'Oh, salahku. Maaf sudah mengganggumu. Aku lupa aku hanya ada ketika kamu membutuhkan sesuatu dariku.',
  'Bodoh kok dipiara, kambing tuh dipiara biar gemuk.',
  'Kamu terdengar lebih merdu ketika mulutmu tertutup.',
  'Daripada kamu mau makan teman, jangan lupa tambahkan nasi biar makin kenyang.',
  'Kamu tuh lucu banget, udah tau salah kok malah ngotot.',
  'Omonganmu seperti parfum isi ulang, wangi tapi palsu.',
  'Pasti kamu capek karena harus pakai make up di dua wajah sekaligus.',
  'Konon jika jodoh adalah tulang rusuk, maka mantan sudah menjadi fosil alias tulang belulang.',
  'Bekerjalah seperti tuyul, ia tidak kelihatan, tidak butuh pujian, tidak gila jabatan, dan tidak pula cari perhatian, tapi hasilnya JELAS.',
  'Kamu kok seperti tahi cicak, neng, mukanya putih tapi lehernya hitam.',
  'Kata orang cinta itu buta, tapi nyatanya cinta bisa melihat mana yang tampan dan mana yang buruk rupa.',
  'Berjuangnya sama aku, giliran sudah berhasil kamu berpaling.',
  'Aku tidak kehilanganmu, kamu yang kehilanganku. Kau akan mencari sosokku pada setiap pacar yang kau kencani, tapi kau tidak akan menemukanku.',
  'Kamu mengingatkanku pada receh gopean. Bermuka dua dan nggak terlalu berharga.',
  'Kalau berbohong dan berselingkuh adalah sebuah pekerjaan, kamu pasti sudah menjadi jutawan.',
  'Buanglah mantan pada orang yang lebih membutuhkan.',
  'Perasaan terbaik adalah melihatmu sekarang bersama dengan seseorang yang wajahnya seperti baru saja ditendang pakai kaleng biskuit.',
  'Maaf aku alergi dengan yang namanya balikan sama mantan.',
  'Aku tidak akan pernah sedih kehilangan dirimu, justru bahagia karena tahu siapa kamu sebenarnya.',
  'Apa benar mantan itu singkatan dari manis, tapi setan?',
  'Baru putus aja udah punya pacar baru lagi, kok kamu tuh kaya rumah petak yang murah, sih.',
  'Jika ada seorang teman mengatakan kamu PINTAR', 'jangan sombong. Belum tentu teman tersebut mengatakan yang sebenarnya.',
  'Contohlah tukang parkir, walaupun punya banyak mobil tapi dia nggak sombong! Karena dia tahu semua itu hanya titipan.',
  'Lihatlah ke atas sebagai motivasi bukan untuk jadi sombong, dan melihat ke bawah agar lebih bersyukur bukan untuk menjadi rendah diri.',
  'Kepala lo lebih besar dari mulut lo, tapi kenapa omong kosong lo lebih besar dari cara berpikir lo?',
  'Orang sombong biasanya suka mengatakan hal berlebihan yang sebenarnya tidak ada padanya.',
  'Bergayalah sesuai dompetmu, wahai anak muda.',
  'Sama-sama berasal dari tanah, sama-sama nginjek tanah dan bakal balik lagi ke tanah. Jadi buat apa sombong?',
  'Orang sombong sebenarnya pengecut karena ia tak berani bergaul dengan orang yang lebih hebat dengan dirinya.',
  'Yang lagi cantik jangan sombong, itu cantik sebentar doang. Tua dikit itu cantik sudah hilang, jadi jangan sombong ya cantik.',
  'Orang sombong itu ibarat orang yang berdiri di atas gunung. Dia melihat orang lain kecil, tapi dia tidak sadar orang lain melihatnya kecil juga.',
  'Katanya move on, tapi ternyata masih sibuk stalking mantan.',
  'Jangan berkata dia hanya temanmu. Bukankah kita dulu juga berawal dari sebuah pertemanan?',
  'Hanya karena aku bersamamu sepanjang waktu, bukan berarti kamu bisa menyia-nyiakan aku.',
  'Sudah punya pacar masih juga cari perhatian orang lain, gak bahagia ya lu?',
  'Jadi siapa yang ada dalam handphonemu? Kalau sedang bersamaku kau selalu sibuk dengan handphonemu, tapi kalau aku jauh darimu pesanku lama kau balas.',
  'Hubungan akan karam jika terlalu banyak penumpang di dalamnya.',
  'Kamu sih cuma mau dimengerti dan dipahami tanpa belajar untuk mengerti dan memahami.',
  'Cie,- yang chatnya kalah penting sama game Mobile Legend.',
  'Ternyata lebih gampang update status daripada kasih kabar.',
  'Di zaman now screenshot lebih dipercaya daripada omongan.',
  'Kebohongan yang diceritakan terlalu sering lama-lama akan terasa seperti kebenaran.',
  'Tak perlu mengkhawatirkan mereka yang membicarakanmu di belakang. Mereka ada di belakangmu karena suatu alasan.',
  'Teman datang seiring banyaknya kebutuhan.',
  'Maaf kalau aku menyakiti perasaanmu saat aku bilang kamu bodoh. Aku kira kamu sudah tahu.',
  'Seorang genius sejati takut terlihat tidak sempurna dan biasanya lebih suka diam daripada mengatakan sesuatu yang tidak berarti.',
  'Sayang, kalau kamu mau bermuka dua, paling tidak buatlah salah satunya terlihat cantik.',
  'Semoga suatu hari nanti hidupmu bakal seindah apa yang kamu pamerkan di Facebook.',
  'Miliki lebih dari yang kau tunjukkan, bicaralah lebih sedikit dari yang kamu tahu.',
  'Aku tak butuh teman yang berubah saat aku berubah dan mengangguk saat aku mengangguk. Bayanganku bisa melakukannya dengan lebih baik.',
  'Dunia itu tidak sempit. Kamu saja yang mainnya kurang jauh.',
  'Menjadi suami yang baik sama seperti menjadi komika. Kamu perlu pengalaman selama 10 tahun sebelum dapat menyebut dirimu seorang pemula.',
  'Perempuan itu lebih suka perhatian kecil tapi berkali-kali, daripada perhatian besar tapi cuma sesekali.',
  'Jadilah suami yang baik, yang nggak hobi merayu wanita lain di dunia maya, yang memang banyak yang lebih cantik.',
  'Lebih baik di awal cuek, tapi akhirnya perhatian daripada awalnya perhatian tapi akhirnya cuek.',
  'Betapa indahnya kalau kita saling menghargai dan mengerti. Jangan saling egois dan nggak peduli.',
  'Yang egois kamu, yang selalu disalahkan aku. Yang temperamental kamu, yang selalu sabar aku.',
  'Di balik kesibukanmu, ada yang rela meluangkan waktunya untuk sekadar menunggumu.',
  'Aku tidak mengerti dengan cara berpikirmu. Diamnya istri itu bukan berarti membiarkanmu berbuat sesuka hati dan menyakitiku.',
  'Kalau sayang pasti nggak cuek. Kalau cuek pasti nggak sayang.',
  'Hidup harus bersosialisasi jangan egois. Kalau mau egois mending hidup di hutan.',
  'Mulut dijaga jangan kalah sama pantat deh. Pantat aja kalau mau kentut mikir dulu, ada yang dengerin apa nggak. Masa mulut mau ngomong nggak mikir dulu.',
  'Katanya sih kalau ada orang yang hobinya nyari-nyari kesalahan orang lain, tapi giliran dikritik langsung marah, itu artinya proses evolusi dia dari monyet ke manusia belum selesai dan tidak sempurna.',
  'Aku kangen denganmu, kamu yang dulu, yang baru jelek.',
  'Penampilan yang cantik adalah saat kita merasa nyaman dengan diri sendiri. Saat kita tidak iri dengan orang lain kita akan lebih cantik.',
  'Tidak selalu harus bersama, tapi selalu paham kapan seharusnya ada. Itulah sahabat sebenarnya.',
  'Saya menyukai teman yang memiliki pikiran terbuka karena mereka cenderung membiarkanmu untuk melihat segala masalah dari berbagai sudut pandang.',
  'Lebih baik musuh yang jujur daripada teman palsu.',
  'Kamu harus mengenali teman-teman yang palsu karena itu yang tersulit untuk disadari.',
  'Jangan pernah percaya kepada siapa pun yang menginginkan apa yang kamu dapatkan. Teman atau bukan, iri hati merupakan emosi yang luar biasa.',
  'Kata-kata itu mudah dibuat, seperti angin. Sahabat yang setia sulit untuk ditemukan.',
  'Akan lebih mudah untuk memaafkan orang biasa daripada memaafkan luka yang diberikan dari orang tercinta.',
  'Di balik sakitnya pengkhianatan yang Ku rasa, ku ucapkan terima kasih Padamu. Karena pengkhianatanmu membuat aku tidak lagi berkawan dengan kemunafikan.',
  'Rasa sakit itu mengajariku tentang kedewasaan, berhati-hati, dan menjadi untuk lebih baik lagi.',
  'Terima kasih sudah meninggalkanmu saat aku sendirian. Aku baru sadar kalau aku bisa melakukan semuanya dengan lebih baik tanpamu.',
  'Aku pernah tertikam oleh ilusiku sendiri. Pengkhianatan oleh hatiku yang sibuk menguntai simpul pertanda cinta.',
  'Aku sudah pernah merasakan kepahitan dalam hidup dan yang paling pahit ialah berharap kepada manusia.',
  'Terkadang kamu harus ikhlas dan membiarkan karma mengambil alih.',
  'Alhamdulillah, Tuhan masih sayang kepadaku dengan memperlihatkan siapa dirimu ketika berada di belakangku. Walau hatiku sangat sakit kala itu, tapi aku bersyukur bisa tahu. Bahwa kau adalah orang yang berbahaya.',
  'Pengalaman telah mengajariku mana itu saudara, mana kawan, mana sahabat, mana pengkhianat, mana pecundang, mana yang baik, dan mana yang pura-pura baik.',
  'Perbuatan-perbuatan salah adalah biasa bagi manusia, tetapi perbuatan pura-pura itulah sebenarnya yang menimbulkan permusuhan dan pengkhianatan.',
  'Sudah lama aku ingin pergi darimu, tapi tidak memiliki alasan. Dan sekarang aku ucapkan terima kasih karena pengkhianatan dirimu menciptakan alasan untuk pergi meninggalkan kamu.',
  'Jangan pikir saat kamu dapat menyakitiku, kamu itu terlihat hebat!Ingat, saat itu kamu sudah kehilangan orang yang benar-benar mencintaimu...',
  'Aku berhenti, terima kasih. Semoga akan ada sosok yang mampu mencintaimu sebanyak aku dan menunggumu sesabar caraku. Selamat kehilangan cinta yang paling besar.',
  'Untuk yang pernah menyakitiku, terima kasih telah mengajarkanku arti bersabar dan semoga kamu tidak akan pernah merasakan sakit yang kurasakan.',
  'Tidak bisa dibayangkan tingkah laku dan caramu. Kemarin katanya sayang, eh, ternyata hari ini malah kau berkata sayang dia.',
  'Pengkhianatan itu ibarat lumut yang tumbuh di sela-sela bebatuan, menyelusup dan tumbuh, lalu secara perlahan menghancurkan.',
  'Ketika aku melihatmu, aku selalu berpikir wajah mana yang kamu lihat ketika bercermin.',
  'Salah satu hal yang menggelikan yang terjadi pada manusia, seseorang menyakitimu lalu dia bertingkah seolah-olah kamu yang menyakitinya.',
  'Pengkhianat berawal dari watak penjilat.Penjilat berawal dari watak penjahat.Penjahat berawal dari watak sekarat.Jadi, pengkhianat akan sekarat dunia akhirat.',
  'Aku sudah berniat menaruh hati kepadamu, tapi kamu malah mengecewakan aku terlebih dahulu.', 'Aku memilih untuk sendiri, bukan karena menunggu yang sempurna, tetapi butuh yang tak pernah menyerah.',
	'Seorang yang single diciptakan bersama pasangan yang belum ditemukannya.',
	'Jomblo. Mungkin itu cara Tuhan untuk mengatakan Istirahatlah dari cinta yang salah',
	'Jomblo adalah anak muda yang mendahulukan pengembangan pribadinya untuk cinta yang lebih berkelas nantinya.',
	'Aku bukan mencari seseorang yang sempurna, tapi aku mencari orang yang menjadi sempurna berkat kelebihanku.',
	'Pacar orang adalah jodoh kita yang tertunda.',
	'Jomblo pasti berlalu. Semua ada saatnya, saat semua kesendirian menjadi sebuah kebersamaan dengannya kekasih halal. Bersabarlah.',
	'Romeo rela mati untuk juliet, Jack mati karena menyelamatkan Rose. Intinya, kalau tetap mau hidup, jadilah single.',
	'Aku mencari orang bukan dari kelebihannya tapi aku mencari orang dari ketulusan hatinya.',
	'Jodoh bukan sendal jepit, yang kerap tertukar. Jadi teruslah berada dalam perjuangan yang semestinya.',
	'Kalau kamu jadi senar gitar, aku nggak mau jadi gitarisnya. Karena aku nggak mau mutusin kamu.',
	'Bila mencintaimu adalah ilusi, maka izinkan aku berimajinasi selamanya.',
	'Sayang... Tugas aku hanya mencintaimu, bukan melawan takdir.',
	'Saat aku sedang bersamamu rasanya 1 jam hanya 1 detik, tetapi jika aku jauh darimu rasanya 1 hari menjadi 1 tahun.',
	'Kolak pisang tahu sumedang, walau jarak membentang cintaku takkan pernah hilang.',
	'Aku ingin menjadi satu-satunya, bukan salah satunya.',
	'Aku tidak bisa berjanji untuk menjadi yang baik. Tapi aku berjanji akan selalu mendampingi kamu.',
	'Kalau aku jadi wakil rakyat aku pasti gagal, gimana mau mikirin rakyat kalau yang selalu ada dipikiran aku hanyalah dirimu.',
	'Lihat kebunku, penuh dengan bunga. Lihat matamu, hatiku berbunga-bunga.',
	'Berjanjilah untuk terus bersamaku sekarang, esok, dan selamanya.',
	'Rindu tidak hanya muncul karena jarak yang terpisah. Tapi juga karena keinginan yang tidak terwujud.',
	'Kamu tidak akan pernah jauh dariku, kemanapun aku pergi kamu selalu ada, karena kamu selalu di hatiku, yang jauh hanya raga kita bukan hati kita.',
	'Aku tahu dalam setiap tatapanku, kita terhalang oleh jarak dan waktu. Tapi aku yakin kalau nanti kita pasti bisa bersatu.',
	'Merindukanmu tanpa pernah bertemu sama halnya dengan menciptakan lagu yang tak pernah ternyayikan.',
	'Ada kalanya jarak selalu menjadi penghalang antara aku sama kamu, namun tetap saja di hatiku kita selalu dekat.',
	'Jika hati ini tak mampu membendung segala kerinduan, apa daya tak ada yang bisa aku lakukan selain mendoakanmu.',
	'Mungkin di saat ini aku hanya bisa menahan kerinduan ini. Sampai tiba saatnya nanti aku bisa bertemu dan melepaskan kerinduan ini bersamamu.',
	'Melalui rasa rindu yang bergejolak dalam hati, di situ terkadang aku sangat membutuhkan dekap peluk kasih sayangmu.',
	'Dalam dinginnya malam, tak kuingat lagi; Berapa sering aku memikirkanmu juga merindukanmu.',
	'Merindukanmu itu seperti hujan yang datang tiba-tiba dan bertahan lama. Dan bahkan setelah hujan reda, rinduku masih terasa.',
	'Sejak mengenalmu bawaannya aku pengen belajar terus, belajar menjadi yang terbaik buat kamu.',
	'Tahu gak perbedaan pensi sama wajah kamu? Kalau pensil tulisannya bisa dihapus, tapi kalau wajah kamu gak akan ada yang bisa hapus dari pikiran aku.',
	'Bukan Ujian Nasional besok yang harus aku khawatirkan, tapi ujian hidup yang aku lalui setelah kamu meninggalkanku.',
	'Satu hal kebahagiaan di sekolah yang terus membuatku semangat adalah bisa melihat senyumanmu setiap hari.',
	'Kamu tahu gak perbedaanya kalau ke sekolah sama ke rumah kamu? Kalo ke sekolah pasti yang di bawa itu buku dan pulpen, tapi kalo ke rumah kamu, aku cukup membawa hati dan cinta.',
	'Aku gak sedih kok kalo besok hari senin, aku sedihnya kalau gak ketemu kamu.',
	'Momen cintaku tegak lurus dengan momen cintamu. Menjadikan cinta kita sebagai titik ekuilibrium yang sempurna.',
	'Aku rela ikut lomba lari keliling dunia, asalkan engkai yang menjadi garis finishnya.',
	'PR-ku adalah merindukanmu. Lebih kuat dari Matematika, lebih luas dari Fisika, lebih kerasa dari Biologi.',
	'Cintaku kepadamu itu bagaikan metabolisme, yang gak akan berhenti sampai mati.',
	'Kalau jelangkungnya kaya kamu, dateng aku jemput, pulang aku anter deh.',
	'Makan apapun aku suka asal sama kamu, termasuk makan ati.',
	'Cinta itu kaya hukuman mati. Kalau nggak ditembak, ya digantung.',
	'Mencintaimu itu kayak narkoba: sekali coba jadi candu, gak dicoba bikin penasaran, ditinggalin bikin sakaw.',
	'Gue paling suka ngemil karena ngemil itu enak. Apalagi ngemilikin kamu sepenuhnya...',
	'Dunia ini cuma milik kita berdua. Yang lainnya cuma ngontrak.',
	'Bagi aku, semua hari itu adalah hari Selasa. Selasa di Surga bila dekat denganmu...',
	'Bagaimana kalau kita berdua jadi komplotan penjahat? Aku curi hatimu dan kamu curi hatiku.',
	'Kamu itu seperti kopi yang aku seruput pagi ini. Pahit, tapi bikin nagih.',
	'Aku sering cemburu sama lipstikmu. Dia bisa nyium kamu tiap hari, dari pagi sampai malam.',
	'Hanya mendengar namamu saja sudah bisa membuatku tersenyum seperti orang bodoh.',
	'Aku tau teman wanitamu bukan hanya satu, dan menyukaimu pun bukan hanya aku.',
	'Semenjak aku berhenti berharap pada dirimu, aku jadi tidak semangat dalam segala hal..',
	'Denganmu, jatuh cinta adalah patah hati paling sengaja.',
	'Sangat sulit merasakan kebahagiaan hidup tanpa kehadiran kamu disisiku.',
	'Melalui rasa rindu yang bergejolak dalam hati, di situ terkadang aku sangat membutuhkan dekap peluk kasih sayangmu.',
	'Sendainya kamu tahu, sampai saat ini aku masih mencintaimu.',
	'Terkadang aku iri sama layangan..talinya putus saja masih dikejar kejar dan gak rela direbut orang lain...',
	'Aku tidak tahu apa itu cinta, sampai akhirnya aku bertemu denganmu. Tapi, saat itu juga aku tahu rasanya patah hati.',
	'Mengejar itu capek, tapi lebih capek lagi menunggu\nMenunggu kamu menyadari keberadaanku...',
	'Jangan berhenti mencinta hanya karena pernah terluka. Karena tak ada pelangi tanpa hujan, tak ada cinta sejati tanpa tangisan.',
	'Aku punya sejuta alasan unutk melupakanmu, tapi tak ada yang bisa memaksaku untuk berhenti mencintaimu.',
	'Terkadang seseorang terasa sangat bodoh hanya untuk mencintai seseorang.',
	'Kamu adalah patah hati terbaik yang gak pernah aku sesali.',
	'Bukannya tak pantas ditunggu, hanya saja sering memberi harapan palsu.',
	'Sebagian diriku merasa sakit, Mengingat dirinya yang sangat dekat, tapi tak tersentuh.',
	'Hal yang terbaik dalam mencintai seseorang adalah dengan diam-diam mendo akannya.',
	'Kuharap aku bisa menghilangkan perasaan ini secepat aku kehilanganmu.',
	'Demi cinta kita menipu diri sendiri. Berusaha kuat nyatanya jatuh secara tak terhormat.',
	'Anggaplah aku rumahmu, jika kamu pergi kamu mengerti kemana arah pulang. Menetaplah bila kamu mau dan pergilah jika kamu bosan...',
	'Aku bingung, apakah aku harus kecewa atu tidak? Jika aku kecewa, emang siapa diriku baginya?\n\nKalau aku tidak kecewa, tapi aku menunggu ucapannya.',
	'Rinduku seperti ranting yang tetap berdiri.Meski tak satupun lagi dedaunan yang menemani, sampai akhirnya mengering, patah, dan mati.',
	'Kurasa kita sekarang hanya dua orang asing yang memiliki kenangan yang sama.',
	'Buatlah aku bisa membencimu walau hanya beberapa menit, agar tidak terlalu berat untuk melupakanmu.',
	'Aku mencintaimu dengan segenap hatiku, tapi kau malah membagi perasaanmu dengan orang lain.',
	'Mencintaimu mungkin menghancurkanku, tapi entah bagaimana meninggalkanmu tidak memperbaikiku.',
	'Kamu adalah yang utama dan pertama dalam hidupku. Tapi, aku adalah yang kedua bagimu.',
	'Jika kita hanya bisa dipertemukan dalam mimpi, aku ingin tidur selamanya.',
	'Melihatmu bahagia adalah kebahagiaanku, walaupun bahagiamu tanpa bersamaku.',
	'Aku terkadang iri dengan sebuah benda. Tidak memiliki rasa namun selalu dibutuhkan. Berbeda dengan aku yang memiliki rasa, namun ditinggalkan dan diabaikan...',
	'Bagaimana mungkin aku berpindah jika hanya padamu hatiku bersinggah?',
	'Kenangan tentangmu sudah seperti rumah bagiku. Sehingga setiap kali pikiranku melayang, pasti ujung-ujungnya akan selalu kembali kepadamu.',
	'Kenapa tisue bermanfaat? Karena cinta tak pernah kemarau. - Sujiwo Tejo',
	'Kalau mencintaimu adalah kesalahan, yasudah, biar aku salah terus saja.',
	'Sejak kenal kamu, aku jadi pengen belajar terus deh. Belajar jadi yang terbaik buat kamu.',
	'Ada yang bertingkah bodoh hanya untuk melihatmu tersenyum. Dan dia merasa bahagia akan hal itu.',
	'Aku bukan orang baik, tapi akan belajar jadi yang terbaik untuk kamu.',
	'Kita tidak mati, tapi lukanya yang membuat kita tidak bisa berjalan seperti dulu lagi.',
	'keberadaanmu bagaikan secangkir kopi yang aku butuhkan setiap pagi, yang dapat mendorongku untuk tetap bersemangat menjalani hari.',
	'Aku mau banget ngasih dunia ke kamu. Tapi karena itu nggak mungkin, maka aku akan kasih hal yang paling penting dalam hidupku, yaitu duniaku.',
	'Mending sing humoris tapi manis, ketimbang sok romantis tapi akhire tragis.',
	'Ben akhire ora kecewa, dewe kudu ngerti kapan waktune berharap lan kapan kudu mandeg.',
	'Aku ki wong Jowo seng ora ngerti artine I Love U', 'Tapi aku ngertine mek Aku tresno awakmu.',
	'Ora perlu ayu lan sugihmu, aku cukup mok setiani wes seneng ra karuan.',
	'Cintaku nang awakmu iku koyok kamera, fokus nang awakmu tok liyane mah ngeblur.',
	'Saben dino kegowo ngimpi tapi ora biso nduweni.',
	'Ora ketemu koe 30 dino rasane koyo sewulan.',
	'Aku tanpamu bagaikan sego kucing ilang karete. Ambyar.',
	'Pengenku, Aku iso muter wektu. Supoyo aku iso nemokne kowe lewih gasik. Ben Lewih dowo wektuku kanggo urip bareng sliramu.',
	'Aku ora pernah ngerti opo kui tresno, kajaba sak bare ketemu karo sliramu.',
	'Cinta aa ka neng moal leungit-leungit sanajan aa geus kawin deui.',
	'Kasabaran kaula aya batasna, tapi cinta kaula ka anjeun henteu aya se epna.',
	'Kanyaah akang moal luntur najan make Bayclean.',
	'Kenangan endah keur babarengan jeung anjeun ek tuluy diinget-inget nepi ka poho.',
	'Kuring moal bakal tiasa hirup sorangan, butuh bantosan jalmi sejen.',
	'Nyaahna aa ka neg teh jiga tukang bank keur nagih hutang (hayoh mumuntil).',
	'Kasabaran urang aya batasna, tapi cinta urang ka maneh moal aya beakna.',
	'Hayang rasana kuring ngarangkai kabeh kata cinta anu aya di dunya ieu, terus bade ku kuring kumpulkeun, supaya anjeun nyaho gede pisan rasa cinta kuring ka anjeun.',
	'Tenang wae neng, ari cinta Akang mah sapertos tembang krispatih; Tak lekang oleh waktu.',
	'Abdi sanes jalmi nu sampurna pikeun anjeun, sareng sanes oge nu paling alus kanggo anjeun. Tapi nu pasti, abdi jalmi hiji-hijina nu terus emut ka anjeun.',
	'Cukup jaringan aja yang hilang, kamu jangan.',
	'Sering sih dibikin makan ati. Tapi menyadari kamu masih di sini bikin bahagia lagi.',
	'Musuhku adalah mereka yang ingin memilikimu juga.',
	'Banyak yang selalu ada, tapi kalo cuma kamu yang aku mau, gimana?',
	'Jam tidurku hancur dirusak rindu.',
	'Cukup China aja yang jauh, cinta kita jangan.',
	'Yang penting itu kebahagiaan kamu, aku sih gak penting..',
	'Cuma satu keinginanku, dicintai olehmu..',
	'Aku tanpamu bagaikan ambulans tanpa wiuw wiuw wiuw.',
	'Cukup antartika aja yang jauh. Antarkita jangan.', 'Kamu suka kopi nggak? Aku sih suka. Tau kenapa alesannya? Kopi itu ibarat kamu, pahit sih tapi bikin candu jadi pingin terus.', 'Gajian itu kayak mantan ya? Bisanya cuman lewat sebentar saja.', 'Kata pak haji, cowok yang nggak mau pergi Sholat Jumat disuruh pakai rok aja.', 'Kamu tahu mantan nggak? Mantan itu ibarat gajian, biasa numpang lewat dong di kehidupan kita.', 'Aku suka kamu, kamu suka dia, tapi dia sayangnya nggak ke kamu. Wkwkw lucu ya? Cinta serumit ini.', 'Google itu hebat ya? Tapi sayang sehebat-hebatnya Google nggak bisa menemukan jodoh kita.', 'Terlalu sering memegang pensil alis dapat membuat mata menjadi buta, jika dicolok-colokkan ke mata.', 'Saya bekerja keras karena sadar kalau uang nggak punya kaki buat jalan sendiri ke kantong saya.', 'Jika kamu tak mampu meyakinkan dan memukau orang dengan kepintaranmu, bingungkan dia dengan kebodohanmu.', 'Selelah-lelahnya bekerja, lebih lelah lagi kalau nganggur.', 'Kita hidup di masa kalau salah kena marah, pas bener dibilang tumben.', 'Nggak ada bahu pacar? Tenang aja, masih ada bahu jalan buat nyandar.', 'Mencintai dirimu itu wajar, yang gak wajar mencintai bapakmu.', 'Katanya enggak bisa bohong. Iyalah, mata kan cuma bisa melihat.', 'Madu di tangan kananmu, racun di tangan kirimu, jodoh tetap di tangan tuhan.', 'Selingkuh terjadi bukan karena ada niat, selingkuh terjadi karna pacar kamu masih laku.', 'Netizen kalau senam jempol di ponsel nggak pakai pendinginan, pantes komennya bikin panas terus.', 'Jodoh memang enggak kemana, tapi saingannya ada dimana-mana.',
'Perasaan aku salah terus di matamu. Kalu gitu, besok aku pindah ke hidungmu.', 'Jomblo tidak perlu malu, jomblo bukan berarti tidak laku, tapi memang tidak ada yang mau.', 'Jika doamu belum terkabul maka bersabar, ingatlah bahwa yang berdoa bukan cuma kamu!', 'Masih berharap dan terus berharap lama-lama aku jadi juara harapan.', 'Manusia boleh berencana, tapi akhirnya saldo juga yang menentukan.', 'Statusnya rohani, kelakuannya rohalus.', 'Kegagalan bukan suatu keberhasilan.', 'Tadi mau makan bakso, cuma kok panas banget, keliatannya baksonya lagi demam.', 'Aku juga pernah kaya, waktu gajian.', 'Aku diputusin sama pacar karena kita beda keyakinan. Aku yakin kalau aku ganteng, tapi dia enggak.', 'Masa depanmu tergantung pada mimpimu, maka perbanyaklah tidur.', 'Seberat apapun pekerjaanmu, akan semakin ringan jika tidak dibawa.', 'Jangan terlalu berharap! nanti jatuhnya sakit!', 'Ingat! Anda itu jomblo', 'Gak tau mau ngetik apa', 'When lu udah berusaha ngelupain dia yang gabakal mungkin lu miliki, dan sial nya malah ketemu di dalam mimpi','Jika tidak bisa bersatu denganmu setidaknya dunia pernah menjadi saksi bahwa aku benar benar mencintaimu','Seharusnya dri dlu jngn berharap lebih kpd seseorang','Lebih baik tersakiti,daripada harus menyakiti','Hidup bukan sebuah perlombaan, nikmati aja setiap proses nya','Kita punya harapan tapi semesta punya kenyataan','Ternyata maksain komunikasi sama seseorang yang ga ada perasaan lebih sama kita itu nguras energi banget ya,','Dipaksa baik baik saja diatas bumi yang sudah tidak baik baik saja','Terkadang otak kita sudah beradaptasi tanpa kehadiran dia tapi hati sangat sulit untuk kehilangan dia','Malam yg tenang tapi tidak dengan pikiran','Ngentod knp dunia ga berpihak sama gw','Kubaca kembali chat lama kita kemudian aku tersenyum dan akhirnya aku menangis','Sudah kubilang payung hanya bisa dipakai untuk dua orang. Jika ada yang ketiga, maka salah satunya harus siap di guyur hujan beserta badainya. Tapi ini bukan tentang','Mau balik lagi? Maaf hubungan ini tidak bisa berlanjut lagi hehe','Feling lonley cape?,ya istirahat karna tuhan tau yang baik gak bikin kamu lonley','Cape sama dunia nt terus mungkin Tuhan sudah menyiapkan jalan terbaik buat kamu', 'Senja selalu cantik kecuali saat kau patah hati.',
  'Aku masih rindu. Namun senja tak ingin lama bertamu.',
  'Ada yang tak tenggelam ketika senja datang, yakni rasa.',
  'Karena senja selalu menerima langit apa adanya.',
  'Setiap senja selalu menjanjikan kita awal yang baru.',
  'Senja telah mengajarkanku apa arti dari mengikhlaskan.',
  'Biar lelah, tapi dia tetap indah. Itulah senja.',
  'Senja tak pernah salah, hanya kenangan yang membuatnya basah.',
  'Hanya senja yang tau cara berpamitan dengan indah.',
  'Senja, perpaduan yang sungguh indah bagi alam semesta.',
  'Selepas senja, aku kembali menjadi manusia yang menutupi air mata dengan gelak tawa.',
  'Senjaku mulai menepi ke peraduannya.',
  'Karena senja tak pernah memintamu menunggu.',
  'Entah mana yang lebih indah, senja yang mulai memerah atau senyummu yang mulai merekah.',
  'Senja tak pernah membenci awan kelabu yang sering menutupinya.',
  'Jadilah seperti senja yang kehadirannya selalu membuat ketenangan dan kepergiannya selalu membuat kerinduan.',
  'Kamu seperti senja,terasa menyenangkan namun tak bertahan lama.',
  'Aku hanya dapat menikmati kehangatan senja yang tak akan pernah untuk menikmati kehangatan pelukanmu.',
  'Senja telah mengajarkan ku apa arti dari mengikhlaskan.',
  'Kamu bagaikan senja di sore hari, indah sesaat kemudian menghilang.',
  'Senja mengajarkan kita bahwa keindahan tak harus datang lebih awal.',
  'Senja tak pernah salah, hanya kenangan yang membuatnya basah.',
  'Kenyataanya senja tetaplah senja. Dia tak punya rasa, dia memberi indah sesaat kepada penikmatnya, lalu pergi begitu saja.',
  'Di antara senja dan keheningan tempat ini, mengingatmu menjadi kesibukan kecil yang membahagiakan.',
  'Di ujung senja yang sudah hampir hilang kali ini aku masih menanti sebuah kabar dan ku tak tahu harus berapa lama ku menunggu.',
  'Untuk luka yang terhapus senja, untuk duka yang makin meraja, yakinlah hati agar membaja, bisikan lembut dengan senyuman manja, Insyaallah bersama Allah semuanya akan baik-baik saja.',
  'Saat senja menyapa, aku menyadari bahwa masih banyak hal indah yang Tuhan ciptakan selain Kamu.',
  'Demi matahari senja yang menggantung manis manja di cakrawala, demi kebaikan dan ketulusan yang telaten diberikan semesta, dan demi ragam nama-nama Tuhan baik yang akrab maupun asing di telinga kita, sesungguhnya, manusia, adalah mahkluk yang merugi. Kecuali, ia yang mau belajar pada masa silam, berbuat yang terbaik di masa sekarang, dan menyiapkan segala sesuatu di masa depan, dengan keyakinan paling yakin pada terwujudnya sebuah impian.',
  'Tuhan, bersama tenggelamnya matahari senja ini, redakanlah kekecewaan dan kemarahan di hati ini. Sabarkanlah aku. Aamiin.',
  'Nikmat Allah mana yang kau dustakan disenja ini wahai saudara-saudaraku semua.',
  'Di tengah angin senja yang mendesak, aku merasakan kekuasaan waktu, yang tanpa pandang bulu mengubah segala-galanya.',
  'Terkadang senja mengingatkan pada rumah, pada orang-orang yang membuat hati kita rindu untuk pulang.',
  'Salah satu nikmat Allah yang sampai detik ini bisa kurasakan adalah masih bisa bernapas dan menghirup segarnya udara senja.',
  'Salam senja dan Magrib. Doa kita kepada yang maha kuasa hanya taubat jawabannya, dosa kita kepada sesama berminta maaf penawarnya.',
  'Gelombang adzan mendayu meminang senja. Di sanalah, Tuhan melahirkan segala rindu.',
  'Engkau terkadang datang seperti jingga di kala senja, datang dengan keindahan berlalu menyisakan kegelapan.',
  'Senja: Mengajarkan kita bahwa yang indah pasti akan tenggelam.',
  'Senja pergi secara perlahan, karena ia tahu pergi secara tiba-tiba hanya menyakiti siapapun yang menikmatinya.',
  'Walau senja tinggalkan keindahan dan pergi, ia selalu datang kembali di esok hari. Tak seperti kamu yang lebih indah dari senja tapi pergi entah kemana.',
  'Ku mencintai kau seperti senja. Dengan keindahannya, tanpa durasinya.',
  'Jangan mengulangi kesalahan yang sama, karena masih banyak kesalahan kesalahan lain yang perlu dicoba.',
  'Terima kasih senja, kau telah menampakkan bahwa perpisahan tak semuanya menyakitkan. Dan kepergian tampak begitu indah tanpa kehangatan.',
  'Senja itu seperti kita, singkat dan bahagia.',
  'Aku hanyalah penikmat kehangatan senja yang tak akan bisa menikmati kehangatan pelukanmu.',
  'Hari ini aku belajar dari senja bahwa yang indah dan mempesona akan hilang dan tenggelam pada waktunya.',
  'Tanaman palsuku mati karena aku tidak berpura pura menyiramnya.',
  'Jangan rindu berat, kamu nggak akan kuat. Biar aku saja yang merindukanmu sekalipun bertambah berat badanku.',
  'Bermimpilah setinggi langit, jika kamu terjatuh berarti tidurmu kurang ke tengah.',
  'Dusk is proof that no matter what happens, everyday can end beautifully.',
  'From the twilight I learned that every beautiful things had to go through all the painful things.',
  'Twilight drops her curtain down, and pins it with a star. Lucky Maud Montgomery.',
  'Dusk teaches us that life is not always bright and shining.',
  'Twilight comes in a beautiful way. As beautiful as God ways in meet us.',
  'Every sunset bring a promise for a new dawn. -Ralph Waldo Emerson',
  'Dusk teaches us to appreciate all the great things the sun gives us.',
  'Dont forget that beautiful twilight needs blackened clouds.',
  'And dusk makes us understand the meaning of the word willing',
  'Twilight fell: The sky turned to a light, dusky purple littered with tiny silver stars. J.K. Rowling',
  'Pengagum senja, penyesap kopi, penikmat rindu, penimba ilmu, peninggi badan, pemanjat sutet, pembuka simontok, penyembah tutup botol.',
  'Tangannya menjadi pengganti tanganku untuk menuntunmu Pundaknya menjadi pengganti pundakku untukmu bersandar. Biarlah gemercik gerimis, carik senja, secangkir teh, dan bait lagu menjadi penggantimu.',
  'Mulai mempertanyakan alam raya, galaksi, planet-planet dan eksistensi saya di muka bumi ketika pagi-pagi belum juga ingin buang air besar.',
  'Jodoh tak akan ke mana-mana terlebih dahulu sebelum akhirnya menetap.',
  'Jatuh hati tidak pernah bisa memilih. Tuhan memilihkan. Kita hanyalah korban. Kecewa adalah konsekuensi, bahagia adalah bonus.',
  'Hujan dan gebetan itu mirip. Ada yang mengaku suka, tapi hanya memandangnya dari tempat duduk yang hangat, berkata-kata romantis tanpa pernah mau bersinggungan. Ada yang betulan suka, mengalahkan rasa tidak nyaman, langsung berinteraksi dengannya meski berisiko sakit.',
  'Enak atau tidaknya ucapan selamat malam dan selamat pagi itu tergantung siapa yang mengucapkan.',
  'Denganmu, basa-basi terasa berisi.',
  'Absurd sekali, kita. Cerita berjam-jam, lalu hilang kabar berhari-hari. Merindu diam-diam, hingga tidak lagi saling mencari.',
  'Aku lelah sembunyi, lelah merindukanmu dalam sunyi. Tanganku jangan dijabat, baiknya digenggam saja. Tak cuma jadi sahabat, jadi kekasihmu juga.',
  'Jangan pernah lupa, bahwa awan menghitam adalah yang membuat senja terlihat sempurna.',
  'Meski senja tiba di ujung mata, rindu enggan tinggalkan kita, tak peduli dengan siapa menanti malam, rindu ini senantiasa menyapa.',
  'Ketika senja mulai tenggelam, ku mulai menyadari kamu yang paling berarti, dan ketika sinar matahari menyapa ku sadari kamu hanya mimpi.',
  'Senjaku berlari mengejar ketinggalannya, menyusuri setapak di tepian jurang menganga, di bawahnya riuh ombak berirama lara.',
  'Jika kamu senja, maka aku jingga. Muncul bersama, hilang pun juga.',
  'Matahari yang tenggelam akan mengajarkan pada kita, agar bisa menghargai apa yang diberikan matahari untuk kita.',
  'Senja begitu cepat berganti, dan sampai saat ini kau tetap kunanti.',
  'Senja memang begitu indah, namun cahaya mentari tetap tak tergantikan, meski dengan lilin yang bersinar sangat terang sekalipun.',
  'Saat jingga bersetubuh dengan gelap, sepasang mata sibuk kemasi air matanya; seakan takut, senja mencuri rindu miliknya.',
  'Senja mengajarkan pada kita, bahwa kehidupan tak selalu berjalan dengan cemerlang dan bersinar.', 'Indonesia adalah Tempat ditemukannya ular terpanjang di dunia yaitu, Python Reticulates sepanjang 10 meter di Sulawesi',
'Suatu penyakit yang disebut “Exercise-Induced Anaphylaxis” harfiah menyebabkan orang menjadi ‘alergi’ untuk berolahraga',
'Pada Sept1909 malam hari, warga Jakarta beruntung menyaksikan Aurora Borealis di langit yg biasanya hanya di kutub ( Prof. Truls L Hansen)',
'Bromelain yang terkandung dalam Nanas bila dikonsumsi berlebihan bagi wanita hamil bisa memicu kontraksi dini bahkan keguguran',
'Secara resmi setiap tanggal 6 Oktober di Jepang merayakan Tom Cruise Day',
'Jembatan suramadu (surabaya-madura) adalah jembatan terpanjang di Asia Tenggara (5438 m)',
'Burung umumnya tidak berkicau apabila mereka hinggap di tanah (Hummingbirdworld)',
'Orang sherpa di Nepal menganjurkan orang memakan bawang putih utk mencegah dan mengobati rasa tidak nyaman yg disebabkan ketinggian gunung',
'Teka-teki silang terbesar yang pernah diterbitkan memiliki 2631 pertanyaan mendatar dan 2922 pertanyaan menurun',
'Rafflesia Arnoldii yang tumbuh di Sumatera adalah bunga terbesar di dunia. Ketika bunganya mekar, diameternya mencapai 1 meter',
'Tertawa dan bahagia meningkatkan imun, terutama produksi sel-sel pembunuh alamiah yang membantu melindungi tubuh dari penyakit',
'Orang yang membayangkan suara baru yang belum pernah didengar, atau menggabungkan sebuah melodi matanya akan bergerak ke kir',
'Kecoa kentut setiap 15 menit dan terus mengeluarkan gas metana (kentut) selama 18 jam setelah kematian',
'Menara Eiffel dibangun oleh Alexandre Eiffel, dan sebagian besar biayanya ditanggung oleh dia',
'Rata-rata orang di dunia jatuh cinta sebanyak 7 kali dulu sebelum ditakdirkan menikah',
'Mengoleskan jeruk nipis dapat mencerahkan bagian lutut / siku yang hitam',
'Ken Edwards seorang pria asal Inggris memegang rekor Guinness untuk makan 36 kecoa dalam 1 menit',
'Energi yang dihasilkan oleh angin ribut (topan) selama 10 menit lebih besar dibandingkan energi dari bom saat perang',
'Lagu kebangsaan Yunani mempunyai 158 bait',
'Kata “depp” dalam bahasa Jerman artinya “idiot”',
'Bobby Tufts (4 tahun) adalah Wali Kota termuda di dunia saat ini (Wali Kota Dorset, Minnesota, AS)',
'Menghisap rokok sambil makan cokelat dapat membunuh racun yang terdapat pada rokok tersebut. [penelitian kedokteran di Universitas Lampung]',
'Di zaman penjajahan Belanda, hukuman orang yg berzina adlh ditangkap dan dicorengkan arang pd hidungnya. Inilah asal usul “Hidung Belang”',
'Kebanyakan orang lebih percaya terhadap kemampuan kepemimpinan seseorang jika orang itu memiliki badan yang lebih tinggi. [inilah .com]',
'Dalam setiap inci persegi permukaan smartphone terdapat skitar 25.107 kuman, artinya smartphone lebih kotor dr kloset. [Laporan dr Proporta]',
'Kebiasaan sibuk memotret dan mengunggah foto makanan di sosial media, beresiko seseorang menjadi gendut. [Dr. Valerie Taylor]',
'Anak yang gemar berolahraga lebih cerdas dibandingkan yang tidak. [penelitian di Michigan State University]',
'Kelurahan Air Jamban adalah nama kelurahan di kecamatan Mandau, kabupaten Bengkalis, provinsi Riau, Indonesia',
'Kata “Poli” berarti Banyak dan “Tics” berarti Makhluk Pengisap Darah. Jadi kata Politics (politik) berarti Banyak Makhluk Pengisap Darah',
'Musik dapat membuat otak bahagia dan kebanyakan mendengarkan musik dapat membuat perut cepat lapar',
'Mendengarkan musik irama lambat saat tidur terbukti mampu meningkatkan kemampuan memori otak. [penelitian di Universitas Tubingen Jerman]',
'Pulau Giliyang di Sumenep, Jawa Timur disebut sbg pulau “Awet Muda” karena pulau ini memiliki kandungan oksigen terbaik di dunia. [tempo co]',
'Morology / Morologi adalah studi tentang percakapan konyol.',
'Hormon Cinta hanya bertahan 4 tahun, sisanya dorongan seks. [penelitian di University of Mexico]',
'Letusan gunung Tambora mengilhami penemuan sepeda, karena bnyk hewan transportasi menjadi mati akibat dr prubahan cuaca yg ekstrem saat itu',
'Tertawa sebanyak 100 kali setara dengan mendayung selama 10 menit. [Dr William Fry dari Stanford Medical School]',
'Studi menunjukkan penggemar musik heavy metal ternyata lebih bisa meredam emosi negatif dan lebih ekspresif. [Sciencedaily]',
'Orang yang terlalu sering begadang memiliki performa otak seperti 7 tahun lebih tua dari usia aslinya. [dailymail.',
'Di Italia, dalam aturannya minuman Cappuccino hanya boleh di minum sebelum waktu siang',
'Hormon Cinta hanya bertahan 4 tahun, sisanya dorongan seks. [penelitian di University of Mexico]',
'Letusan gunung Tambora mengilhami penemuan sepeda, karena bnyk hewan transportasi menjadi mati akibat dr prubahan cuaca yg ekstrem saat itu',
'Tertawa sebanyak 100 kali setara dengan mendayung selama 10 menit. [Dr William Fry dari Stanford Medical School]',
'Studi menunjukkan penggemar musik heavy metal ternyata lebih bisa meredam emosi negatif dan lebih ekspresif. [Sciencedaily]',
'Orang yang terlalu sering begadang memiliki performa otak seperti 7 tahun lebih tua dari usia aslinya. [dailymail]',
'Koin ¥ 1 (Yen Jepang) bisa mengapung di atas air',
'Di Cape Town, Afrika Selatan, remaja laki-laki yang memiliki gigi ompong dianggap tampan / maskulin',
'Memeluk orang yg disayangi dpt membantu menurunkan tekanan darah, mengurangi stres dan kecemasan, bahkn dpt meningkatkan memori. [Dailymail]',
'Kata “Mouse” (tikus) berasal dari turunan Bahasa Sansekerta “Mus” yang berarti “pencuri”. 48. Berjalan kaki atau bersepeda ke sekolah mempertajam konsentrasi siswa di kelas dan tetap bertahan sekitar 4 jam kemudian. [Medical Daily]',
'Menurut riset pasar global Euromonitor International, pria Korea adalah pria yang paling suka bersolek dari pria lain di dunia',
'Rata-rata orang akan merasa 100 persen sehat / fit hanya 61 hari dalam setahun. [penelitian di Inggris]',
'Polydactyl Cat adalah jenis kucing yang memiliki jempol di kaki mereka',
'Hanya dengan mengurangi brightness dari televisi, anda mampu berhemat lebih dari Rp 1,5 juta setahun. [kompas]',
'Di Jerman, tahanan yg ingin meloloskan diri dr penjara adl bukan mrupakn perbuatan ilegal. Krn itu salah1 naluri dasar manusia untuk kebebasan',
'Wanita merasa diri mereka terlihat paling jelek dan terlihat lebih tua pada hari Rabu pukul 15.30.  [studi baru dari St Tropez] Expand',
'Orang yang rutin bermain video game ternyata memiliki penalaran yang baik dibanding kebanyakan orang (detikHealth)',
'Nama “Gorila” berasal dari kata Yunani “Gorillai” yang berarti “perempuan berbulu”',
'IBM mengatakan bahwa dalam kurun waktu 5 tahun ke depan, komputer bakal mirip manusia yang bisa melihat, mendengar, mencium dan merasakan',
'Selama abad ke-13, kata “nice” sebenarnya berarti “stupid”, “senseless” dan “foolish”',
'49% dari pemilik Smartphone adalah jomblo. (Survei, “2012 Online User Behavior and Engagement Study”)',
'Gazzarella adalah keju mozzarella yang terbuat dari susu kucing. 61. Rata-rata orang melihat / mengecek ponselnya sekitar 150 kali sehari. (Laporan Nokia pada MindTrek 2010)',
'Tertawa dapat meningkatkan aktivitas antibodi sekitar 20%, juga membantu untuk menghancurkan virus dan sel-sel tumor',
'Fobia matematika (mathematics anxiety) memicu respon yang sama di otak sbg rasa sakit fisik. Gejalanya yaitu melihat angka saja sudah nyeri',
'Karakter kartun Bugs Bunny diberi pangkat kehormatan sersan-mayor di Korps Marinir AS pada akhir Perang Dunia II. (wikipedia)',
'Menurut etiket internasional, sebuah jabat tangan yang tepat dan baik harus berlangsung selama sekitar 3 detik & dilepaskan setelah goyang',
'Ketika kita sedang jatuh cinta, otak akan memproduksi dopamin ekstra, bahan kimia yang membuat seseorang menjadi gembira berlebihan',
'“Mwahahaha” dan “lolz” telah ditambahkan ke Kamus Inggris Oxford',
'Menurut penelitian, pria cenderung menurunkan volume suaranya ketika ia berbicara dg seseorang yg ia cintai, sementara perempuan sebaliknya',
'Di Perancis, jajanan Arum Manis (Rambut Nenek) disebut “Barbe á Papa” yang berarti “Jenggot Ayah”',
'Menurut penelitian, PR terlalu banyak sebenarnya dapat menyebabkan siswa menjadi stres, depresi & mendapat nilai lebih rendah',
'Hangry adalah penggabungan kata dari “Hungry” dan “Angry”, di pakai ketika anda sedang lapar dan marah',
'Kentut dari bakteri membuat keju swiss memiliki lubang-lubang',
'Orang yang merasa kesepian memiliki kemungkinan mengalami kepikunan 70-80% lebih tinggi. (Journal of Neurosurgery Neurologi and Psychiatry)',
'Mendengarkan musik benar-benar dapat mengurangi rasa sakit kronis hingga 20% dan membantu meringankan depresi hingga 25%. (sciencedaily)',
'Tanduk badak terbuat dari keratin',
'Jerapah memiliki lidah sepanjang 21 inchi',
'Sepeda pertama dibuat pada tahun 1817 dibuat tanpa pedal',
'Rechendorfer Yusuf adalah orang pertama yang berhasil menempatkan karet penghapus di atas sebuah pensil',
'Balon mainan yang pertama kali terbuat dari karet vulkansir',
'Satu ujung pensil dapat menulis 50.000 kata dalam bahasa Inggris',
'Terdapat hampir 900 jenis kelelawar di dunia',
'Tangan kanan orang hidup lebih lama dari tangan kiri',
'Banyak orang yang dibunuh oleh keledai',
'Seekor buaya tidak dapat mengeluarkan lidah',
'Semut tidak tidur',
'Beruang kutub bertangan kidal',
'Astronot tidak diperbolehkan untuk makan kacang-kacangan sebelum mereka pergi ke ruang angkasa karena buang angin/kentut dalam pakaian ruang angkasa mengakibatkan kerusakan',
'Dengan menaikkan kaki Anda perlahan dan berbaring ke belakang, Anda tidak dapat terperosok ke dalam pasir',
'Pemogokan cahaya di bumi sekitar 6.000 kali per menit',
'Lobster memiliki darah biru',
'Seorang pria mengatakan rata-rata 4.850 kata dalam 24 jam',
'Kuku ibu jari tumbuh lambat dan kuku jari tengah yang tercepat',
'Kecap sebelumnya dijual sebagai obat',
'Cokelat dapat membunuh anjing',
'Produk pertama yang memiliki barcode adalah Wrigley’s gum',
'Kanada dalam bahasa India berarti Desa Besar',
'Seseorang menghasilkan 100 pound sel darah merah dalam hidupnya',
'Pita karet terpanjang adalah di kulkas',
'Ada 293 cara untuk menukar dolar',
'“Dreamt” adalah satu-satunya kata yang berakhir dengan ‘mt’',
'Orang yang cerdas memiliki kadar seng dan tembaga di rambut mereka',
'69% orang Amerika menggunakan internet dan hanya 5,5% dari India',
'Plastik dibutuhkan 500 tahun untuk terurai',
'Amerika telah memiliki 30,30% bandara di dunia & India hanya 0,70%',
'Total wilayah permukaan bumi adalah 197 juta mil persegi',
'Cahaya matahari mencapai bumi membutuhkan waktu sekitar 8 jam 3 detik',
'Penduduk di dunia telah meningkat 3,1 miliar dalam 40 tahun terakhir',
'Sekitar 180 juta kartu Valentine tersebar per tahunnya',
'Orang yang berusia di atas 100 di AS meningkat dari 4.000 pada tahun 1960 menjadi 55.000 pada tahun 1995',
'Seekor kucing dapat berlari 20 km per jam',
'Seekor cheetah dapat berlari 76 km per jam',
'Katak yang terbesar di dunia adalah Goliath Frog',
'Tidak ada dua zebra yang belangnya serupa',
'Terdapat hampir 50 jenis kangguru',
'Joeys adalah nama yang diberikan kepada anak kanguru',
'Woodpecker dapat mematuk 20 kali dalam satu menit',
'Lidah seekor Chameleon adalah dua kali panjang tubuhnya sendiri',
'10% dari populasi dunia adalah tangan kiri',
'Pada abad pertengahan di Eropa, garam sangat mahal harganya, sehingga disebut sebagai “emas putih”',
'Mengunyah permen karet dapat meningkatkan kemampuan berpikir cepat dan kewaspadaan hingga 10 persen. [Jurnal Brain and Cognition]',
'Wanita yang sedang stres selama kehamilannya cenderung melahirkan anak-anak yang pemarah. [Institute of Psychiatry, King College London]',
'Disarankan supaya membeli sepatu pada sore hari. Sebab, setelah seharian berjalan, di sore hari kaki akan membesar 5-8 persen',
'Musik memiliki kemampuan untuk memperbaiki kerusakan otak serta mengembalikan kenangan yang hilang. [cracked .com]',
'Perbandingan jumlah rayap dan manusia di dunia adalah 10 :',
'Ayam yang sudah terpenggal lehernya masih mampu lari sepanjang lapangan bola sebelum benar-benar mati',
'Berdiri lama tanpa menekuk lutuk sama sekali akan membuat kita pingsan',
'Kuda Nil kentut lewat mulut',
'Pohon kelapa membunuh 150 orang tiap tahun, lebih banyak daripada hiu',
'Jika kita memelihara ikan mas dalam ruangan yang gelap, warnanya akan berubah putih',
'Tikus beranakpinak sangat cepat dan dalam waktu 18 bulan, dua tikus dapat memiliki lebih dari 1 juta keturunan',
'Kita bernafas kira-kira 23.000 kali setiap hari',
'Tahukah anda? Llanfairpwllgwyngyllgogerychwyrndrobwlll, adalah nama sebuah desa di Wales Utara, Inggris. Sulit dibaca bukan?',
'Ada sekitar 10ribu jenis apel di dunia Kutu rambut sebenarnya lebih suka hidup di kulit kepala yang bersih dari pada yang kotor',
'Umur dari capung adalah 24 jam',
'Pria kehilangan 40 helai rambut tiap hari. wanita 70 helai',
'Jika bersin terlalu keras dapat meretakkan tulang iga. JIka mencoba menahan bersin, bisa mengalami pecah pembuluh nadi di kepala dan leher trus mati . jika memaksa mata terbuka saat bersin, bola mata bisa meloncat keluar',
'Kalajengking bisa dibunuh dengan menyiramnya dengan cuka,mereka akan murka dan menyengat dirinya sendir',
'Kentut sapi termasuk penyebab utama global warming',
'Gerakan Bruce Lee sangat cepat sehingga mereka harus melambatkan film agar kita bisa melihat semua gerakannya',
'Siput bisa tidur selama 3 tahun',
'Jika kita berdiri di dasar sumur, kita bisa melihat bintang walaupun di siang hari',
'Tehnik mengaduk terbaik bukan dengan gerakan memutar, tapi dengan gerakan huruf W',
'Tiap tahun, bulan menjauh 3.82 cm dari bumi',
'Riset membuktikan, memakan pisang bisa menambah daya ingat',
'Orang yang alergi bahan latex, biasanya alergi kiwi juga',
'Ilmu tentang perkembangan apel disebut Pomology',
'Kita bisa mematangkan Mangga dengan cepat dengan cara memasukkan ke dalam paperbag bersama dengan pisang matang',
'Antioksidans pada apel lebih besar 5x dari pisang',
'Hanya 1 dari 5 orang australia makan apel tiap hari',
'Kiwi memiliki nama lain Chinese Gooseberry',
'Mangga masih 1 family dengan tanaman Poison Ivy',
'Pelaut inggris mengonsumsi air jeruk nipis untuk menghindari mabuk laut',
'Pelaut inggris disebut juga Limeys karena suka minum air jeruk nipis',
'Nanas mengandung Bromelain yang berguna mencegah bir dingin berawan',
'Kutu rambut sebenarnya lebih suka hidup di kulit kepala yang bersih dari pada yang kotorUmur dari capung adalah 24 jam',
'1 pohon apel rata2 bisa menghasilkan 500buah apel',
'25% kandungan dalam apel adalah Udara. makanya apel bisa mengapung',
'Lebih dari 60juta Ton apel dihasilkan di dunia per periode tertentu',
'Kiwi ditetapkan sebagai buah kebangsaan di Cina',
'Pear akan berubah menjadi hitam sekali jika disimpan pada lingkungan yang kurang oksigen',
'Markisa pertama kali ditemukan di Brazil',
'Riset membuktikan bahwa makan apel bisa mengurangi risiko kena kanker',
'Biji apel merupakan racun ringan namun tidak berbahaya bagi manusia',
'Jeruk adalah buah yang paling umum di dunia',
'Beberapa negara di dunia melatih bangsa monyet untuk memetik kelapa',
'Ada lebih dari 400jenis kiwi di Cina',
'Bahasa gaul di australia “She’s Apple” bukan berarti “Dia (wanita) manis” tetapi berarti “Semuanya baik2 saja”',
'Nanas yang belum matang adalah racun',
'Kiwi memiliki nama asli Yang Tao (Sunny Peach)',
'Makan pisang ketika makan nasi dapat membantu ibu hamil terhindar dari Morning Sickness',
'Plum jepang sebenarnya berasal dari Cina',
'Plum bisa tumbuh di semua benua kecuali antartika',
'Memerlukan tenaga 50lembar daun untuk menghasilkan 1buah apel dalam 1pohon',
'Makan plum membantu meningkatkan penyerapan zat besi dalam tubuh',
'Anggur dapat meledak jika dimasukkan ke dalam microwave',
'Pisang mengandung vitamin B6 yang bisa mengontrol kadar gula dalam darah, dan membangkitkan mood',
'1nanas bukan 1buah, tetapi terdiri atas lebih dari 200anak buah (fruitlets)',
'Jeruk nipis tidak mengandung segala jenis lemak, natrium, dan kolestrol',
'Menanam semangka dalam kotak akan menghasilkan semangka kotak',
'Dilihat dari beratnya, semangka adalah buah yang paling diminati di USA',
'Pohon kelapa entah kenapa disebut “Tree of Life”',
'Bunga pohon markisa adalah Bunga kebangsaan negara Paraguay',
'Semangka adalah sepupunya Terong, Labu, dan Squash',
'Menanam 1biji buah jeruk bisa menghasilkan lebih dari 1 pohon',
'Bagian dalam kulit pisang bisa untuk menyemir sepatu kulit',
'Bagian dalam kulit pisang juga bisa digunakan untuk menghilangkan gatal bekas gigitan nyamuk dengan cara menggosokkannya',
'Di Kerala, India selatan, Bunga kelapa digunakan untuk upacara Pernikahan',
'Kulit Plum dipercaya memiliki efek Laxative',
'Pisang kaya akan vitamin B-Complex yang bisa menenangkan sistem saraf',
'Tidak ada yang se-rima dengan “orange” (jeruk)',
'Salah satu spesies markisa yang buahnya berwarna ungu bisa melakukan fertilisasi sendiri',
'Pisang bisa meningkatkan kadar Serotonin yang bisa melawan depresi',
'Semakin besar “Navel” pada Jeruk Navel, semakin manis buahnya',
'Markisa yang berkerut adalah markisa yang paling manis',
'Radiasi dari 1 batang rokok sama dgn radiasi 2000x X-ray',
'Sepatu boot awalnya dikhususkan untuk berperang',
'Sebelum Masehi bahasa inggrisnya adalah B.C (Before Christ). Setelah Masehi adalah A.D (Anno Domini)',
'Ikan hiu kehilangan gigi lebih dari 6000buah setiap tahun, dan gigi barunya tumbuh dalam waktu 24 jam',
'Julius Caesar tewas dengan 23 tikaman',
'Nama mobil Nissan berasal dari bahasa jepang Ni : 2 dan San : 3. Nissan : 23',
'Jerapah dan tikus bisa bertahan hidup lebih lama tanpa air dari pada unta',
'Perut memproduksi lapisan lendir setiap dua minggu agar perut tidak mencerna organnya sendiri',
'98% dari perkosaan dan pembunuhan dilakukan oleh keluarga dekat atau teman korban',
'Semut dapat mengangkat beban 50 kali tubuhnya',
'Deklarasi Kemerdekaan Amerika ditulis diatas kertas marijuana',
'Titik diatas huruf i disebut ‘title’',
'Sebutir kismis yang dijatuhkan kedalam gelas berisi sampanye segar akan bergerak naik turun dalam gelas',
'Benjamin Franklin anak bungsu dari orangtua bungsu keturunan ke 5 dalam keluarga bungsu',
'Triskaidekaphobia adalah ketakutan pada 13. Paraskevidekatriaph obia adalah ketekukan pada hari jumat tanggal 13 (bisa terjadi antara 1-3 kali setahun). di Italia, 17 adalah angka sial di Jepang angka sial adalah 4',
'Lidah jerapah panjangnya sekitar 50 cm',
'Mulut menghasilkan 1 liter ludah setiap hari',
'Kita bernafas kira-kira 23.000 kali setiap hari',
'Kata ZIP (kode pos) adalah kepanjangan dari ‘Zoning Improvement Plan’',
'Coca-Cola mengandung Coca (yang merupakan zat aktif pada kokain) dari tahun 1885 sampai 1903',
'Rata-rata kita bicara 5000 kata tiap hari (walaupun 80% nya kita bicara pada diri sendiri)',
'Seandainya kuota air dalam tubuh kita berkurang 1%, kita langsung merasa haus',
'4 simbol raja pada kartu remi melambangkan 4 raja yang etrkenal di jaman masing-masing: Sekop = David/Raja Daud ; Keriting = Alexander the Great/Iskandar Agung ; Hati = Charlemagne/ Raja Prancis ; Wajik =Julius Caesar',
'Seumur hidup kita meminum air sebanyak kurang lebih 75.000 liter',
'Setiap orang, termasuk kembar identik, sidik jari dan tekstur lidahnya tidak ada yang sama',
'Titik merah pada 7-Up logo berasal dari penemunya yang bermata merah. Dia seorang albino',
'Pria kehilangan 40 helai rambut tiap hari. wanita 70 helai',
'Tanda ’save’ pada Microsoft Office programs menunjukan gambar floppy disk dengan shutter terbalik',
'Albert Einstein dan Charles Darwin,keduanya menikah dengan sepupu pertama mereka (Elsa Löwenthal dan Emma Wedgewood)',
'Unta punya 3 kelopak mata',
'Sehelai rambut di kepala kita mempunyai masa tumbuh 2 sampai 6 tahun sebelum diganti dengan rambut baru',
'Seseorang masih akan sadar selama 8 detik setelah dipenggal',
'Otot yang bekerja paling cepat ditubuh kita adalah otot dikelopak mata yang membuat kita berkedip. kita bisa berkedip 5kali dalam sedetik',
'Coklat dapat membunuh anjing,karena langsung mempengaruhi jantung dan susunan syarafnya',
'Tanpa dicampur ludah di dalam mulut, kita tidak akan merasakan rasa makanan',
'Kuku jari tangan tumbuh 4kali lebih cepat daripada kuku kaki',
'13% orang di dunia adalah kidal',
'Hampir semua lipstik mengandung sisik ikan',
'Bayi yang baru lahir berat kepalanya 1/4 dari berat tubuhnya',
'Kita sebenarnya melihat dengan otak. mata hanya berupa kamera yang mengirim data ke otak. 1/4 bagian dari otak digunakan untuk mengatur kerja mata',
'Kalajengking bisa dibunuh dengan menyiramnya dengan cuka,mereka akan murka dan menyengat dirinya sendiri',
'Tahun 1830an saus tomat biasa dijual sebagai obat',
'Tiga monyet bijak punya nama: Mizaru (See no evil), Mikazaru (Hear no evil), and Mazaru (Speak no evil)',
'India mempunyai Undang-undang hak untuk sapi',
'Jika bersin terlalu keras dapat meretakkan tulang iga. JIka mencoba menahan bersin, bisa mengalami pecah pembuluh nadi di kepala dan leher trus mati . jika memaksa mata terbuka saat bersin, bola mata bisa meloncat keluar',
'Nama negara Filipina berasal dari nama Raja Phillip',
'Saudi Arabia berasala dari nama Raja Saud',
'Anak-anak mempunyai 20 gigi awal. Orang dewasa punya 32',
'Karena langkanya logam, piala Oscars yang dibagikan pada perang dunia ke II terbuat dari kayu',
'Setiap Siklus 11 tahun, kutub magnet pada matahari bertukar tempat. Siklus ini dinamakan “Solarmax”',
'Ada 318,979,564, 000 kemungkinan kombinasi pembukaan pertama pada catur',
'Ada lebih dari 300 bakteri pembentuk karang gigi',
'Macan adalah anggota terbesar dalam keluarga kucing',
'Nomer “172? dapat ditemukan pada uang kertas 5 dollar amerika, pada gambar semak-semak dibawah Lincoln Memorial',
'Pohon kelapa membunuh 150 orang tiap tahun. Lebih banyak daripada hiu',
'Pada poster film ‘Pretty Woman’ Julia Robets terlalu pendek untuk bisa sejajar dengan Richard Gere. Maka digunakan model Shelley Michelle sebagai tubuh Julia',
'Daerah kutub kehilangan matahari selama 186 hari dalam setahun',
'Kode Telephone Internasional untuk Antartica adalah 672',
'Bom pertama sekutu dijatuhkan di Berlin pada perang dunia ke II. Membunuh satu-satunya gajah di Kebun Binatang Berlin',
'Rata-rata hujan jatuh dengan kecepatan 7 mil per jam',
'Butuh 10 tahun bagi Leonardo Da Vinci untuk melukis Mona Lisa. Lukisan itu tidak ditandai dan di beri tanggal. Leonardo dan Mona mempunya susunan tulang yang persis sama dan menurut sinar X, ada 3 versi lukisan dibawah lukisan itu',
'Nama dari kembar gemini adalah Castor dan Pullox',
'Gerakan Bruce Lee sangat cepat sehingga mereka harus melambatkan filam agar kita bisa melihat semua gerakannya',
'Satu kilo dari berat badan kita mengandung 7000 kalori',
'Darah sama kental dengan air laut',
'Air laut di samudra Atlantik lebih asin dari pada di samudra Pasifik',
'Topeng tokoh Michael Myers di film horor ‘Helloween’ sebenernya topeng tokoh Captain Kirk (Star Trek) yang di cat putih, karena kurang dana',
'Nama asli butterfly (kupu-kupu) adalah flutterby',
'Bayi lahir setiap 7 detik',
'Satu dari 14 wanita Amerika berambut pirang asli. Prianya hanya satu dari 17',
'The Olympic adalah saudara dari kapal Titanic, dan melayani dengan selamat selama 25 tahun',
'Saat Titanic karam, 2228 orang ada di dalamnya. Hanya 706 yang selamat',
'Di Amerika, seseorang didiagnosa menderita AIDS tiap 10 menit. Di Afrika, seseorang meninggal karena AIDS tipa 10 menit',
'Sampai usia 6 bulan, bayi bisa menelan dan bernapas secara bersamaan. Orang dewasa tidak bisa',
'Alasan kenapa diiklan jam kebanyakan jarum menunjuk pukul 10.10, karena jam seperti sedang tersenyum',
'Tiap tahun bulan menjauh 3.82 cm dari bumi',
'Saat kita bertahan hidup dan tidak ada bahan makanan, sabuk kulit dan sepatu keds adalah makanan terbaik untuk dimakan karena mengandung cukup gizi untuk hidup sementara',
'Dalam satu tetes air mengandung 50 juta bakteri',
'Dengan menaikan kaki pelan2 dan berbaring tenang dengan punggung lurus, kita tidak akan tenggelam di pasir hisap',
'Satu dari 10 orang hidup di suatu pulau',
'Memakan seledri membuang kalori lebih banyak dari pada kalori yang terkandung dalam seledri itu sendiri',
'Lobster dapat hidup selama 100 tahun',
'Permen karet tidak dijual di Disney Land',
'Mangunyah permen karet saat mengupas bawang mencegah kita menangis',
'Rahang kucing gak bisa bergerak kekiri dan kanan',
'Nama Artic (kutub utara) berarti beruang dalam bahasa Yunani (Arktos), dan memang beruang kutub hanya ada di kutub utara',
'Jika kira berdiri di dasar sumur, kita bisa melihat bintang walaupun di siang hari',
'Suara yang kita dengar dari dalam kerang bukan suara ombak laut, tapi suara aliran darah dalam kepala kita',
'Orang kebanyak yang menderita ketakutan pada ruang terbuka (kenophobia) daripada ketakukan pada ruang tertutup (claustrophobia) ',
'Tehnik mengaduk terbaik bukan dengan gerakan memutar, tapi dengan gerakan huruf W',
'Adegan band yang terus bermain musik saat Titanic tenggelam adalah kisah nyata',
'Buku Guinness Book of Records memegang rekor sebagai buku yang paling banyak dicuri dari perpustakaan',
'35% dari orang yang ikut kontak jodoh lewat internet, sudah menikah',
'CocaCola dulu berwarna hijau',
'Secara fisik, babi tidak bisa melihat ke langit',
'Semua beruang kutub kidal',
'Kelelawar selalu belok kiri jika terbang keluar gua',
'Jim Henson pertama kali memakai kata “Muppet”. Kombinasi dari “marionette” dan “puppet”',
'Gajah satu-satunya hewan yang tidak bisa meloncat',
'The Michelin man (figur berbaju dan bertopi putih diiklan Michelin) bernama Mr. Bib. nama aslinya Bibendum pada iklan pertama tahun 1896',
'Kita tidak bisa menjilat siku kita sendiri',
'Kata “lethologica” menggambarkan saat dimana kita tidak bisa mengingat apa yang kita inginkan',
'Sekitar 14% pecandu yang menggunakan jarum suntik, positif HIV',
'Kalimat yang bisa dibaca sama dari depan dan belakang (racecar, kayak, tamat) disebut “palindrome” ',
'Siput bisa tidur selama 3 tahun',
'Diatas khatulistiwa melintas sekitar 200 satelit asing, termasuk satelit mata-mata',
'Orang di Cina lebih banyak yang berbahasa Inggris dari pada orang di Amerika',
'Karena pengaruh rotasi bumi, kalau kita melempar kearah barat, lemparan kita akan lebih jauh jatuhnya dari pada kearah timur',
'Satu dari 9000 orang menderita albino',
'Kursi listrik ditemukan oleh seorang dokter gigi',
'Kita berulang tahun bersama 9 juta orang dari seluruh dunia',
'Setiap manusia dalam hidupnya rata-rata habis untuk menunggu dilampu merah selama 2 minggu',
'Botol aqua dan tempat makan plastik baru bisa terurai dengan sempurna dalam tanah setelah 50.000 tahun',
'Kucing bisa membuat lebih dari 100 bunyi vokal, anjing hanya bisa sekitar 10',
'Gigi berang-berang tak pernah berhenti ',
'Kelelawar adalah satu-satunya mamalia yang bisa terbang',
'Jika boneka Barbie adalah manusia, ukurannya adalah 39-23-33 (99-58,5-84 cm). Tingginya sekitar 215 cm dan punya leher 2kali lebih panjang daripada manusia normal',
'Tikus beranakpinak sangat cepat dan dalam waktu 18 bulan, dua tikus dapat memiliki lebih dari 1 juta keturunan',
'Memakai Headphone selama 1 jam dapat mengembangbiakan bakteri dalam kuping 700 kali lebih cepat',
'Seekor Babon bernama ‘Jackie’ menjadi prajurit resmi dalam angkatan bersenjata Afrika Selatan pada Perang Dunia I',
'Bibliophile adalah sebutan untuk kolektor buku-buku langka. Bibliopole adalah penjual buku-buku langka',
'Jantung ikan paus biru berdenyut 9 kali dalam semenit',
'Arabic numerals bukan berasal dari Arab, tapi diciptakan di India',
'Kupu-kupu melihat dengan 12000 mata',
'Bulan February tahun 1865 adalah satu-satunya bulan dalam catatan sejarah yang tidak sempat mengalami bulan purnama',
'Ayam yang sudah terpenggal lehernya masih mampu lari sepanjang lapangan bola sebelum benar-benar mati',
'Kecoak bisa hidup 9 hari tanpa kepala, dan akan mati karena kelaparan',
'Di Bumi, satu tahun adalah 365 hari. Di planet Merkurius satu tahun adalah 2 hari',
'Umur dari capung adalah 24 jam',
'Pada Usia 3 bulan janin manusia mulai terbentuk sidik jari',
'Butuh waktu 6 bulan untuk kuku kaki tumbuh dari bawah paling bawah sampai ujung kuku',
'Daya ingat ikan hanya 3 detik',
'Bulan purnama 9 kali tebih terang daripada bulan setengah',
'Untuk setiap patung memorial orang diatas kuda, jika 2 kaki depan kuda mengangkat, maka orang tersebut tewas dalam pertempuran, jika satu kaki kuda yang terangkat, maka orang tersebut meninggal karena luka dalam pertempuran, jika 4 kakinya menginjak tanah, orang tersebut meninggal secara normal',
'Beruang dewasa dapat lari secepat kuda',
'Tulang kuda lebih banyak 18 buah dari tulang manusia',
'Ubur-ubur terdiri dari 95% air',
'Kulit Zebra adalah putih yang bergaris hitam',
'Kecuali manusia dan monyet, semua mamalia buta warna',
'Biji apel mengandung sianida',
'Tikus dan kuda tidak bisa muntah',
'Penguin adalah burung yang tidak bisa terbang tapi bisa berenang',
'Astronot dilarang mengkonsumsi kacang sebelum menjelajah ruang angkasa karena jika buang angin dalam baju khusus astronot dapat membahayakan mereka',
'Winston Churchill lahir di toilet wanita saat acara dansa',
'Sebelum ada pesawat jet, Jetlag disebut Boatlag',
'Kucing berkeringat melalui telapak kakinya (terutama saat mendengar gonggongan anjing)',
'Kucing tidak bisa merasakan rasa manis',
'Coklat meleled dalam mulut karena titik lelehnya adalah 35 derajat celcius',
'Dalam perang dahulu, orang yang buta warna dibutuhkan dalam tim pendeteksi kamuflase di militer',
'Sapi tidak punya gigi atas',
'Hedenophobic berarti takut akan kesenangan',
'Pendeta Mesir kuno mencabuti setiap helai rambut dan bulu dari badan mereka',
'Buaya tidak bisa menjulurkan lidah',
'Kentut sapi termasuk penyebab utama global warming',
'Semut selalu jatuh miring ke kanan jika diberi racun serangga',
'Kucing rumah benci bau lemon dan semua yang berbau sitrus',
'Donal Bebek dilarang beredar di Finlandia karena Donal tidak pakai celana',
'Nama asli Donal bebek adalah Donald Flauntleroy Duck',
'Indra perasa kupu-kupu ada dikakinya',
'Dry Ice tidak meleleh, tapi menguap',
'Mata burung unta lebig besar dari otaknya',
'Bintang laut tidak punya otak',
'Tiap manusia punya telinga yang berbeda',
'Telur segar tenggelam diair, telur yang kadaluarsa mengambang',
'80% dari seluruh binatang di dunia adalah serangga',
'Kacang adalah salah satu bahan untuk membuat dinamit',
'Ratu Elizabeth I menderita Anthophobia (takut akan mawar)',
'RSVP adalah Respondez s’il Vous Plait yang artinya ‘mohon jawaban’',
'Mata manusia yang sehat (tidak buta warna) dapat menbedakan 500 jenis warna abu-abu',
'Ikan mas yang bunting disebut ‘twit’',
'Eropa adalah benua tanpa padang pasir',
'Lalat meloncat mundur saat akan terbang',
'Sekeor kucing memiliki 32 otot pada tiap telinga',
'A honeybee can fly at fifteen miles per hour',
'Macan mempunyai kulit yang belang,bukan hanya bulu yang belang',
'A “jiffy” is the scientific name for 1/100th of a second',
'Hanya 3 malaikat, Gabriel, Michael dan Lucifer yang disebut dalam injil',
'Kambing mempunya pupil mata segi empat',
'Novel pertama yang menggunakan mesin tik adalah Tom Sawyer',
'Hamster sangat suka makan jangkrik',
'Pemantik ditemukan sebelum korek api',
'Rata-rata dalam setiap batang permen coklat terdapat serangga yang meleleh bersamanya',
'Tanduk badak terbuat dari rambutnya yang mengeras',
'Perang paling singkat dalam sejarah adalah perang Zanzibar and England tahun 1896. Zanzibar menyerah setelah 38 menit',
'Kutu rambut sebenarnya lebih suka hidup di kulit kepala yang bersih dari pada yang kotor',
'Kulit beruang kutub sebenarnya hitam. Bulunya berwarna bening, dan tampak putih di salju',
'Elvis mempunyai saudara kembar bernama Garon, yang meninggal saat lahir, maka nama tengah Elvi adalah Aron, untuk menghormati saudaranya',
'Landak punya sidik jari yang mirip manusia',
'Kuda Nil kentut lewat mulut',
'Shakespeare yang menemukan kata “assassination” dan “bump”',
'Mahluk yang bisa tersipu-sipu hanya manusia',
'Jika kita memelihara ikan mas dalam ruangan yang gelap, warnanya akan berubah putih',
'Wanita berkedip dua kali lebih banyak dari pria',
'Nama Jeep (jip) diampil dari singkatan “GP”, bahasa militer untuk General Purpose',
'Orang yang menggunakan tangan kanan, kira-kira, 9 tahun lebih panjang umur dari orang kidal',
'Jika semua emas dalam laut ditambang, setiap manusia didunia bisa mendapat emas 20 kg masing2',
'Jika lever manusia berhenti bekerja, manusia akan mati dalam 8 samapai 24 jam',
'Seorang “quidnunc” adalah sebutan untuk orang yang selalu ingin tahu gosip terbaru',
'Jika matahari tiba-tiba padam, butuh 8 menit bagi manusia untuk menyadarinya',
'Leonardo Da Vinci yang menemukan gunting, helikopter, dan banyak alat lainnya',
'Dalam 4000 tahun, tidak ada jenis binatang peliharaan baru',
'25% dari tulang manusia ada di kaki',
'David Sarnoff adalah orang yang menerima sinyal Titanic dan meyelamatkan ratusan nyawa. Dia akhirnya menjadi kepala jaringan radio, the National Broadcasting Company (NBC)',
'Kira-kira 100 orang tersedak ballpoint tiap tahun',
'Jika kita terkunci diruang yang kedap udara, kita aka lebih dulu mati keracunan co2 dari pada kekerangan o2',
'Jika kita kehilangan satu mata, kita akan kehilangan 1/5 dari pengelihatan kita dan kehilangan seluruh persepsi tentang kedalaman objek',
'Berdiri lama tanpa menekuk lutuk sama sekali akan membuat kita pingsan',
'Bawang putih yang kita gosok di tumit kaki akan meresap dapat dapat tercium dalam nafas kita',
'Dengan merentangkan kedua tangan sejauh mungkin, jarak dari kedua ujung tangan adalah sama dengan tinggi kita',
'Liburan selama sebelas hari berarti kita punya waktu hampir sejuta detik untuk menikmatinya',
'Dalam film Silence of The Lambs, tokoh Hannibal Lecter tidak pernah berkedip',
'Di jepang, warung kopi disebut ‘Kissaten’',
'Merebus telur burung unta butuh waktu 40 menit',
'Jaguar takut pada anjing',
'Gajah hanya tidur 2 jam dalam sehari',
'Johnny Deep takut pada badut',
'Ganymede adalah bulan planet Jupiter, merupakan bulan terbesar di tata surya kita, lebih besar dari planet Merkurius',
'Dalam golf, ‘Bo Derek’ adalah istilah untuk nilai 10',
'Koala punya dua jempol',
'Latte dalam bahasa Italia adalah susu',
'Llanfairpwllgwyngyl lgogerychwyrndro bwlll… adalah nama sebuah desa di Wales Utara, Inggris',
'Di Italia, Micky Mouse lebih dikenal dengan nama ‘ Topolino’',
'Susu sebenarnya lebih menyerupai makanan daripada minuman',
'Ada lebih dari 450 jenis susu di dunia. 240 berasal dari Prancis',
'Nyamuk lebih suka anak-anak daripada orang dewasa',
'Partikel debu didalam rumah sebagian besar berasal dari sel kulit mati',
'Rat-rata orang bergerak 40 kali dalam tidurnya',
'Dalam bahasa Inggris, ‘Naked’ artinya tanpa perlindungan. ‘Nude’ artinya telanjang',
'Broccoli dan kembang kol adalah sayuran yang berupa bunga',
'Anak baru lahir memiliki 350 tulang. Mereka menyatu atau menghilang sampai menjadi 206 pada usia 5 tahun',
'Tidak ada bukti yang pasti siapa yang membangun Taj Mahal',
'Dalam survey terhadap 200000 burung unta selama 80 tahun, tidak ada satupun yang mengubur kepalanya dalam tanah',
'Nail Amstrong melangkah pertama kali di bulan dengan kaki kiri',
'Shuttlecock untuk badminton harus punya 14 bulu',
'Mutiara bisa larut dalam cuka',
'Babi tidak dapat berkeringat karena tidak punya kelenjar keringat. Mereka berlumur lumpur untuk mendinginkan kulitnya',
'Venus dan Uranus adalah planet di tata surya kita yang berputar melawan jarum jam. Jadi matahari terbit dari barat di planet ini',
'Microwave ditemukan setelah seorang ilmuan yang berjalan melewati tabung radar mendapati permen coklatnya meleleh disakunya',
'Ikan hiu kebal terhadap kanker',
'Rusa Santa bernama: Dasher, Dancer, Prancer, Vixen, Comet, Cupid, Donner, dan Blitzen',
'Beberapa jenis cacing pita akan memakan dirinya sendiri jika kelaparan',
'Kita bisa menghela sapi naik tangga, tapi tidak bisa menghela mereka turun tangga',
'Plakat yang ditinggalkan Apollo 11 di bulan berbunyi “Here men from the planet Earth first set foot upon the Moon July 1969, A.D. / WE CAME IN PEACE FOR ALL MANKIND',
'Alpabet Hawai terdiri dari 12 huruf saja',
'Nama paling populer di dunia adalah Muhammad',
'Bola mata kita beratnya sekitar 28 gram',
'Paru-paru kiri lebih kecil dari paru-paru kanan karena memberi tempat terhadap jantung',
'Pinguin hanya ada di kutub selatan, dan tidak bisa menyebrangi equator',
'Kebanyakan orang bisa mendengar lebih baik dengan kuping kanan',
'Vitamin pada buah biasanya terdapat pada kulitnya',
'Rata-rata klakson mobil berbunyi pada nada F',
'Pria lebih mampu membaca tulisan dengan ukuran huruf kecil daripada wanita', 'Dear kamu yang tertulis di halaman defacementku, Kapan jadi pacarku?',
	'Aku rela ko jadi Processor yg kepanasan, asalkan kmu yg jadi heatsink y yg setiap saat bisa mendinginkan ku.',
	'Gak usah nyari celah xss deh, karena ketika kamu ngeklik hatiku udah muncul pop up namamu.',
	'berharap setelah aku berhasil login di hati kamu ga akan ada tombol logout, dan sessionku ga bakal pernah expired.',
	'Masa aku harus pake teknik symlink bypass buat buka-buka folder hatimu yg open_basedir enabled.',
	'Diriku dan Dirimu itu ibarat PHP dan MySQL yang belum terkoneksi.',
	'Jangan cuma bisa inject hatinya,tapi harus bisa patchnya juga. Biar tidak selingkuh sama hacker lain.',
	'Aku memang programmer PHP,tapi aku nggak akan php-in kamu kok.',
	'Eneeeng. | Apache? | Km wanita yg paling Unix yg pernah aku kenal |',
	'Sayang, capslock kamu nyala ya? | ngga, kenapa emangnya? | soalnya nama kamu ketulis gede bgt di hati aku | zzz! smile',
	'Aku deketin kamu cuma untuk redirect ke hati temenmu.',
	'Domain aja bisa parkir, masa cintaku ga bisa parkir dihatimu?',
	'Aku boleh jadi pacarmu? | 400(Bad Request) | Aku cium boleh? | 401(Authorization Required) | Aku buka bajumu yah | 402(Payment Required) sad',
	'kamu tau ga beda y kamu sama sintax PHP, kalo sintax PHP itu susah di hafalin kalo kamu itu susah di lupain',
	'Kamu dulu sekolah SMK ambil kejuruan apa? | Teknik Komputer Jaringan | Terus sekarang bisa apa aja? | Menjaring hatimu lewat komputerku | biggrin',
	'Jika cinta itu Array, maka,cintaku padamu tak pernah empty jika di unset().',
	'SQLI ( Structured Query Love Injection )',
	'aku ingin kamu rm -rf kan semua mantan di otak mu,akulah root hati kamu',
	'Senyumu bagaikan cooler yang menyejukan hatiku ketika sedang overclock.',
	'kamu adalah terminalku, dimana aku menghabiskan waktuku untuk mengetikan beribu baris kode cinta untukmu smile',
	'Aku seneng nongkrong di zone-h, karena disanalah aku arsipkan beberapa website yang ada foto kamunya.',
	'hatiku ibarat vps hanya untukmu saja bukan shared hosting yg bisa tumpuk berbagai domain cinta.',
	'Aku bukanlah VNC Server Tanpa Authentication yg bisa kamu pantau kapan saja.',
	'Jangan men-dualboot-kan hatiku kepadamu.',
	'cintaku kan ku Ctrl+A lalu kan ku Ctrl+C dan kan ku Ctrl+V tepat di folder system hatimu.',
	'KDE kalah Cantiknya, GNOME kalah Simplenya, FluxBox kalah Ringannya, pokonya Semua DE itu Kalah Sama Kamu.',
	'Cintamu bagaikan TeamViewer yang selalu mengendalikan hatiku',
	'cinta kita tak akan bisa dipisahkan walau setebal apapun itu firewall...!!', 'Ada anak kecil bermain batu,\nBatu dilempar masuk ke sumur,\nBelajar itu tak kenal waktu,\nJuga tidak memandang umur.',
'Tanam kacang di pagi hari,\nTumbuh enam layu sebatang,\nKeburukan orang jangan dicari,\nBila kalian sedang puasa. ',
'Akhir bulan mendapat gaji,\nGaji untuk membeli ketupat,\nRajin-rajinlah sholat dan mengaji,\nJanganlah lupa puasa dan zakat. ',
'Waktu daftar hari terakhir,\nWaktu terasa banyak terbuang,\nKamu nggak perlu khawatir,\ncintaku hanya untukmu seorang. ',
'Ada anak kecil bermain batu,\nBatu dilempar masuk ke sumur,\nBelajar itu tak kenal waktu,\nJuga tidak memandang umur. ',
'Seribu bebek di kandang singa,\nhanya satu berwarna belang,\nBeribu cewek di Indonesia,\nhanya engkau yang aku sayang. ',
'Hari minggu pergi ke pasar,\nBeli sayur dan juga beras,\nTiap hari harus belajar,\nPasti akan menjadi cerdas. ',
'Ayam goreng setengah mateng,\nBelinya di depan tugu.\nAbang sayang, abangku ganteng,\nlneng di sini setia menunggu. ',
'Api kecil dari tungku,\nApinya kecil habis kayu.\nSudah lama kutunggu-tunggu,\nkapan kamu bilang I love you. ',
'Seribu bebek di kandang singa,\nhanya satu berwarna belang\nBeribu cewek di Indonesia,\nhanya engkau yang aku sayang. ',
'Pergi memancing saat fajar,\nPulang siang membawa ikan\nSiapa yang rajin belajar\nJadi orang sukses kemudian. ',
'Beli computer itu biasa\nSupaya belajar jadi semangat\nMari kita belajar puasa\nAgar kita jadi kuat ',
'Minum sekoteng hangat rasanya,\nminum segelas ada yang minta.\nLaki-laki ganteng siapa yang punya?\nBolehkah aku jatuh cinta.',
'Raja gagah lagi sakti Laksamana pergi berperang Supaya tidak sesal di hati Janganlah kena perdaya orang ',
'Pergi mendaki Gunung Daik Hendak menjerat kancil dan rusa Bergotong-royong amalan yang baik Elok diamalkan setiap masa',
'Pinang muda dibelah dua Manik-manik mati dirempuh Dari muda sampai ke tua Pengajaran baik jangan diubah ',
'Tegak-tegak cocokkan pancang Pasang bendera bunyikan tabuh Agak-agak mengatai orang Supaya cedera jangan tumbuh ',
'Batang ketumbar dahan-dahan Kelapa jatuh ke tepi bangsal Biarlah sabar dengan perlahan Siapa gopoh nanti menyesal ',
'Kayu bakar dibuat arang Arang dibakar memanaskan diri Jangan mudah menyalahkan orang Cermin muka lihat sendiri ',
'Lepas di jemur baju dilipat Disimpan dalam almari lama Jangan kita tinggalkan sholat Karena sholat tiang agama',
'Ke restoran membeli makan Perginya bersama sang istri Perintah Tuhan ayo kerjakan Larangan Tuhan ayo jauhi',
'Pulau Sumatra pulau Kalimantan Pulau Bali pulau Sumba Shalat lima waktu ayo tegakkan Tiang agama nan utama',
'Membeli beras ke Mang Duloh Membeli semen ke Mang Omat Iman dan takwa kepada Allah Kunci bahagia dunia akhirat',
'Beli bensin satu tangki Bensi dibeli oleh Mak Rosa Bersihkan hati dari dengki Sucikan raga dari dosa'

]